menu:
  Home: / || fas fa-house
  About: /about/ || fas fa-circle-info
  Archives: /archives/ || fas fa-box-archive
  Friends: /friends/ || fa-solid fa-user-group

comments: false

friends:
  他说: https://090909.top/ || 梁栋烨的博客网站。